# Generated by Django 3.2.7 on 2021-09-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_category_recipe_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='extention',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
