# Generated by Django 3.2.7 on 2021-09-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210914_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preface',
            field=models.TextField(blank=True, null=True),
        ),
    ]
